# Generated by Django 2.0 on 2018-12-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talk_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkytalkuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='username'),
        ),
    ]
